language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t kwonmoonsung/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true kwonmoonsung/react-test-app npm run test

after_success:
  - docker build -t kwonmoonsung/docker-frontend ./frontend
  - docker build -t kwonmoonsung/docker-backend ./backend
  - docker build -t kwonmoonsung/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin
  
  - docker push kwonmoonsung/docker-frontend
  - docker push kwonmoonsung/docker-backend
  - docker push kwonmoonsung/docker-nginx

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-fullstack-app"
  env: "Dockerfullstackapp-env-2"
  bucket_name: elasticbeanstalk-ap-northeast-2-466346727417
  bucket_path: "docker-fullstack-app"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY